// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3360.Hyperion_3360_2013.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3360.Hyperion_3360_2013.Robot;
/**
 *
 */
public class  Ascent_HooksOff extends Command {
    public Ascent_HooksOff() {
        requires(Robot.ascentHook);
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.ascentHook.UnlockHook();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.ascentHook.HooksOff();
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return !Robot.ascentHook.HookStatus();
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
